"""'add_f'

Revision ID: 1bb78fc6505e
Revises: 555730dd498e
Create Date: 2020-06-30 17:12:46.737630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bb78fc6505e'
down_revision = '555730dd498e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('orderid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oprice', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('odate', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('orderid')
    )
    op.create_index(op.f('ix_order_orderid'), 'order', ['orderid'], unique=False)
    op.create_table('product',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pname', sa.String(length=500), nullable=True),
    sa.Column('pprice', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('pdate', sa.DateTime(), nullable=True),
    sa.Column('remain', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('oid', sa.Integer(), nullable=True),
    sa.Column('typeid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['oid'], ['official_user.oid'], ),
    sa.ForeignKeyConstraint(['typeid'], ['type.typeid'], ),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('pname')
    )
    op.create_index(op.f('ix_product_pid'), 'product', ['pid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_pid'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_order_orderid'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
