"""1

Revision ID: 558f74c6d5ca
Revises: 5c9a46678b3f
Create Date: 2020-10-21 19:23:25.322230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '558f74c6d5ca'
down_revision = '5c9a46678b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_all_order_orderID'), 'all_order', ['orderID'], unique=False)
    op.drop_index('uid', table_name='all_order')
    op.drop_constraint('all_order_ibfk_1', 'all_order', type_='foreignkey')
    op.drop_column('all_order', 'User_userID')
    op.create_index(op.f('ix_cart_cartID'), 'cart', ['cartID'], unique=False)
    op.drop_index('ix_cart_cid', table_name='cart')
    op.drop_index('pid', table_name='cart')
    op.drop_index('uid', table_name='cart')
    op.drop_constraint('cart_ibfk_1', 'cart', type_='foreignkey')
    op.drop_constraint('cart_ibfk_2', 'cart', type_='foreignkey')
    op.drop_column('cart', 'Product_itemID')
    op.drop_column('cart', 'User_userID')
    op.create_index(op.f('ix_detailed_order_detailed_orderID'), 'detailed_order', ['detailed_orderID'], unique=False)
    op.drop_index('ix_detailed_order_detailedoid', table_name='detailed_order')
    op.drop_index('oid', table_name='detailed_order')
    op.drop_index('orderid', table_name='detailed_order')
    op.drop_index('pid', table_name='detailed_order')
    op.drop_constraint('detailed_order_ibfk_2', 'detailed_order', type_='foreignkey')
    op.drop_constraint('detailed_order_ibfk_4', 'detailed_order', type_='foreignkey')
    op.drop_constraint('detailed_order_ibfk_3', 'detailed_order', type_='foreignkey')
    op.drop_column('detailed_order', 'Product_itemID')
    op.drop_column('detailed_order', 'Official_user_official_userID')
    op.drop_column('detailed_order', 'Order_orderID')
    op.create_index(op.f('ix_official_user_official_userID'), 'official_user', ['official_userID'], unique=False)
    op.drop_index('ix_official_user_oid', table_name='official_user')
    op.create_index(op.f('ix_product_itemID'), 'product', ['itemID'], unique=False)
    op.drop_index('ix_product_pid', table_name='product')
    op.drop_index('oid', table_name='product')
    op.drop_index('typeid', table_name='product')
    op.drop_constraint('product_ibfk_2', 'product', type_='foreignkey')
    op.drop_constraint('product_ibfk_3', 'product', type_='foreignkey')
    op.drop_column('product', 'Type_typeID')
    op.drop_column('product', 'Official_user_official_userID')
    op.create_index(op.f('ix_type_typeID'), 'type', ['typeID'], unique=False)
    op.drop_index('ix_type_typeid', table_name='type')
    op.create_index(op.f('ix_user_userID'), 'user', ['userID'], unique=False)
    op.drop_index('ix_user_uid', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_uid', 'user', ['userID'], unique=False)
    op.drop_index(op.f('ix_user_userID'), table_name='user')
    op.create_index('ix_type_typeid', 'type', ['typeID'], unique=False)
    op.drop_index(op.f('ix_type_typeID'), table_name='type')
    op.add_column('product', sa.Column('Official_user_official_userID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('Type_typeID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('product_ibfk_3', 'product', 'official_user', ['Official_user_official_userID'], ['official_userID'])
    op.create_foreign_key('product_ibfk_2', 'product', 'type', ['Type_typeID'], ['typeID'])
    op.create_index('typeid', 'product', ['Type_typeID'], unique=False)
    op.create_index('oid', 'product', ['Official_user_official_userID'], unique=False)
    op.create_index('ix_product_pid', 'product', ['itemID'], unique=False)
    op.drop_index(op.f('ix_product_itemID'), table_name='product')
    op.create_index('ix_official_user_oid', 'official_user', ['official_userID'], unique=False)
    op.drop_index(op.f('ix_official_user_official_userID'), table_name='official_user')
    op.add_column('detailed_order', sa.Column('Order_orderID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('detailed_order', sa.Column('Official_user_official_userID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('detailed_order', sa.Column('Product_itemID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('detailed_order_ibfk_3', 'detailed_order', 'official_user', ['Official_user_official_userID'], ['official_userID'])
    op.create_foreign_key('detailed_order_ibfk_4', 'detailed_order', 'product', ['Product_itemID'], ['itemID'])
    op.create_foreign_key('detailed_order_ibfk_2', 'detailed_order', 'all_order', ['Order_orderID'], ['orderID'])
    op.create_index('pid', 'detailed_order', ['Product_itemID'], unique=False)
    op.create_index('orderid', 'detailed_order', ['Order_orderID'], unique=False)
    op.create_index('oid', 'detailed_order', ['Official_user_official_userID'], unique=False)
    op.create_index('ix_detailed_order_detailedoid', 'detailed_order', ['detailed_orderID'], unique=False)
    op.drop_index(op.f('ix_detailed_order_detailed_orderID'), table_name='detailed_order')
    op.add_column('cart', sa.Column('User_userID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('Product_itemID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('cart_ibfk_2', 'cart', 'user', ['User_userID'], ['userID'])
    op.create_foreign_key('cart_ibfk_1', 'cart', 'product', ['Product_itemID'], ['itemID'])
    op.create_index('uid', 'cart', ['User_userID'], unique=False)
    op.create_index('pid', 'cart', ['Product_itemID'], unique=False)
    op.create_index('ix_cart_cid', 'cart', ['cartID'], unique=False)
    op.drop_index(op.f('ix_cart_cartID'), table_name='cart')
    op.add_column('all_order', sa.Column('User_userID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('all_order_ibfk_1', 'all_order', 'user', ['User_userID'], ['userID'])
    op.create_index('uid', 'all_order', ['User_userID'], unique=False)
    op.drop_index(op.f('ix_all_order_orderID'), table_name='all_order')
    # ### end Alembic commands ###
