"""1

Revision ID: 590d0e9bcc7f
Revises: 558f74c6d5ca
Create Date: 2020-10-21 19:27:25.645624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590d0e9bcc7f'
down_revision = '558f74c6d5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_all_order_orderID'), 'all_order', ['orderID'], unique=False)
    op.drop_index('uid', table_name='all_order')
    op.create_index(op.f('ix_cart_cartID'), 'cart', ['cartID'], unique=False)
    op.drop_index('ix_cart_cid', table_name='cart')
    op.drop_index('pid', table_name='cart')
    op.drop_index('uid', table_name='cart')
    op.create_index(op.f('ix_detailed_order_detailed_orderID'), 'detailed_order', ['detailed_orderID'], unique=False)
    op.drop_index('ix_detailed_order_detailedoid', table_name='detailed_order')
    op.drop_index('oid', table_name='detailed_order')
    op.drop_index('orderid', table_name='detailed_order')
    op.drop_index('pid', table_name='detailed_order')
    op.create_index(op.f('ix_official_user_official_userID'), 'official_user', ['official_userID'], unique=False)
    op.drop_index('ix_official_user_oid', table_name='official_user')
    op.create_index(op.f('ix_product_itemID'), 'product', ['itemID'], unique=False)
    op.drop_index('ix_product_pid', table_name='product')
    op.drop_index('oid', table_name='product')
    op.drop_index('typeid', table_name='product')
    op.create_index(op.f('ix_type_typeID'), 'type', ['typeID'], unique=False)
    op.drop_index('ix_type_typeid', table_name='type')
    op.create_index(op.f('ix_user_userID'), 'user', ['userID'], unique=False)
    op.drop_index('ix_user_uid', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_uid', 'user', ['userID'], unique=False)
    op.drop_index(op.f('ix_user_userID'), table_name='user')
    op.create_index('ix_type_typeid', 'type', ['typeID'], unique=False)
    op.drop_index(op.f('ix_type_typeID'), table_name='type')
    op.create_index('typeid', 'product', ['Type_typeID'], unique=False)
    op.create_index('oid', 'product', ['Official_user_official_userID'], unique=False)
    op.create_index('ix_product_pid', 'product', ['itemID'], unique=False)
    op.drop_index(op.f('ix_product_itemID'), table_name='product')
    op.create_index('ix_official_user_oid', 'official_user', ['official_userID'], unique=False)
    op.drop_index(op.f('ix_official_user_official_userID'), table_name='official_user')
    op.create_index('pid', 'detailed_order', ['Product_itemID'], unique=False)
    op.create_index('orderid', 'detailed_order', ['Order_orderID'], unique=False)
    op.create_index('oid', 'detailed_order', ['Official_user_official_userID'], unique=False)
    op.create_index('ix_detailed_order_detailedoid', 'detailed_order', ['detailed_orderID'], unique=False)
    op.drop_index(op.f('ix_detailed_order_detailed_orderID'), table_name='detailed_order')
    op.create_index('uid', 'cart', ['User_userID'], unique=False)
    op.create_index('pid', 'cart', ['Product_itemID'], unique=False)
    op.create_index('ix_cart_cid', 'cart', ['cartID'], unique=False)
    op.drop_index(op.f('ix_cart_cartID'), table_name='cart')
    op.create_index('uid', 'all_order', ['User_userID'], unique=False)
    op.drop_index(op.f('ix_all_order_orderID'), table_name='all_order')
    # ### end Alembic commands ###
