"""1

Revision ID: 78d0f6a0307e
Revises: f5c665e3901d
Create Date: 2020-10-21 19:50:51.445696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d0f6a0307e'
down_revision = 'f5c665e3901d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_userID'), 'user', ['userID'], unique=False)
    op.drop_index('ix_user_uid', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_uid', 'user', ['userID'], unique=False)
    op.drop_index(op.f('ix_user_userID'), table_name='user')
    # ### end Alembic commands ###
