"""''

Revision ID: 8d0967ebc8e1
Revises: 9bfe959e16a4
Create Date: 2020-06-30 18:47:07.649393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d0967ebc8e1'
down_revision = '9bfe959e16a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
