"""''

Revision ID: 9bfe959e16a4
Revises: b7ce0fba9df2
Create Date: 2020-06-30 18:18:15.768490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfe959e16a4'
down_revision = 'b7ce0fba9df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detailed_order_ibfk_3', 'detailed_order', type_='foreignkey')
    op.drop_constraint('detailed_order_ibfk_1', 'detailed_order', type_='foreignkey')
    op.create_foreign_key(None, 'detailed_order', 'official_user', ['oid'], ['oid'])
    op.create_foreign_key(None, 'detailed_order', 'product', ['pid'], ['pid'])
    op.drop_constraint('product_ibfk_1', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'official_user', ['oid'], ['oid'])
    op.drop_index('type1', table_name='type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('type1', 'type', ['type1'], unique=True)
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_ibfk_1', 'product', 'official_user', ['oid'], ['oid'], ondelete='CASCADE')
    op.drop_constraint(None, 'detailed_order', type_='foreignkey')
    op.drop_constraint(None, 'detailed_order', type_='foreignkey')
    op.create_foreign_key('detailed_order_ibfk_1', 'detailed_order', 'official_user', ['oid'], ['oid'], ondelete='SET NULL')
    op.create_foreign_key('detailed_order_ibfk_3', 'detailed_order', 'product', ['pid'], ['pid'], ondelete='SET NULL')
    # ### end Alembic commands ###
