"""'non_f'

Revision ID: b7ce0fba9df2
Revises: 1bb78fc6505e
Create Date: 2020-06-30 17:13:16.866049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7ce0fba9df2'
down_revision = '1bb78fc6505e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnumber', sa.Integer(), nullable=True),
    sa.Column('cprice', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['product.pid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_index(op.f('ix_cart_cid'), 'cart', ['cid'], unique=False)
    op.create_table('detailed_order',
    sa.Column('detailedoid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('dprice', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('orderid', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('oid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['oid'], ['official_user.oid'], ),
    sa.ForeignKeyConstraint(['orderid'], ['order.orderid'], ),
    sa.ForeignKeyConstraint(['pid'], ['product.pid'], ),
    sa.PrimaryKeyConstraint('detailedoid')
    )
    op.create_index(op.f('ix_detailed_order_detailedoid'), 'detailed_order', ['detailedoid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detailed_order_detailedoid'), table_name='detailed_order')
    op.drop_table('detailed_order')
    op.drop_index(op.f('ix_cart_cid'), table_name='cart')
    op.drop_table('cart')
    # ### end Alembic commands ###
